name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-12, ubuntu-latest, windows-latest]
        # Add other variables if needed, e.g., architecture
    steps:

      - uses: actions/checkout@v3

      # Checkout the secondary repository only on macOS
      - name: Checkout xray repository
        if: runner.os == 'macOS'
        uses: actions/checkout@v3
        with:
          repository: 'romaxa55/xray'
          path: 'xray'

      - name: Setup Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: '1.23'

      - name: Setup Gomobile (macOS only)
        if: runner.os == 'macOS'
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init

      - name: Build
        run: |
          if [ "${{ runner.os }}" == "macOS" ]; then
            cd xray
            make
            zip -ry XrayKit.xcframework.zip ./xray.xcframework
          elif [ "${{ runner.os }}" == "Linux" ]; then
            # Add Linux build commands here
            echo "Building for Linux..."
            # Example:
            # make linux
          elif [ "${{ runner.os }}" == "Windows" ]; then
            # Add Windows build commands here
            echo "Building for Windows..."
            # Example:
            # make windows
          fi

      - name: Render Template (macOS only)
        if: runner.os == 'macOS'
        run: |
          export TEMP=$(shasum -a 256 xray/XrayKit.xcframework.zip | awk '{ print $1 }')
          export CHECKSUM=${TEMP}
          cd Templates
          sed -i "_bak" "s/VERSION/${{ github.event.inputs.version }}/g" Package.template
          sed -i "_bak" "s/CHECKSUM/${CHECKSUM}/g" Package.template

      - name: Update Package.swift (macOS only)
        if: runner.os == 'macOS'
        run: |
          rm -f Package.swift
          cp ./Templates/Package.template Package.swift

      - name: Commit Changes (macOS only)
        if: runner.os == 'macOS'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "XrayKit Release ${{ github.event.inputs.version }}!!!"
          commit_user_name: Arror
          commit_user_email: hallo.maqiang@icloud.com
          tagging_message: "${{ github.event.inputs.version }}"
          file_pattern: 'Package.swift'

      - name: Upload Release (macOS only)
        if: runner.os == 'macOS'
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: "${{ github.event.inputs.version }}"
          files: xray/XrayKit.xcframework.zip
